#!/bin/bash

#SBATCH --output=output/%j.out
#SBATCH -p GPU,GPU-DEPINFO
#SBATCH --gres=gpu:1
#SBATCH -n 1
#SBATCH -c 1
#SBATCH -N 1
#SBATCH --mem=20G
#SBATCH -x calcul-bigcpu-lahc-4,calcul-gpu-lahc-7,calcul-gpu-lahc-6,calcul-gpu-lahc-2

echo $1
source /home_expes/tools/python/Python-3.8.7_gpu/bin/activate
export CUBLAS_WORKSPACE_CONFIG=:4096:8
export PYTHONUNBUFFERED=1
eval $1
